version: '3'

services:
  server_app:
    image: myblenet/app_server_presets:1.0.1
    ports:
      - "8000:80"
      - "8181:8181"
      - "3333:3333"
      - "3000-3030:3000-3030"
      - "3366:3306"
      - "3307-3365:3306"
      - "8881-8889:8881-8889"
    volumes:
      - ./../app:/usr/local/apache2/htdocs/app
