version: '3'

services:
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - myblenet-app-server-network

  server_app:
    image: myblenet/app_server_presets:1.0.0
    expose:
      - "80"
      - "81"
    ports:
      - "8000:80"
      - "8881:81"
    volumes:
      - ./../app:/usr/local/apache2/htdocs/app
    networks:
      - myblenet-app-server-network

networks: 
  myblenet-app-server-network:
    driver: bridge
