version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "docker"
      MYSQL_DATABASE: "docker"
    ports:
      - 33660:3306
    volumes:
      - ./../mysql_server:/var/lib/mysql
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    ports:
      - 8888:8080
    networks:
      - mysql-compose-network

  server_app:
    image: myblenet/app_server_presets:1.0.0
    ports:
      - 8880:80
    volumes:
      - ./../app:/usr/local/apache2/htdocs/app
    networks:
      - mysql-compose-network

networks: 
  mysql-compose-network:
    driver: bridge
